[mongodb]
mongodb-dev.rakesh.bond

[catalogue]
catalogue-dev.rakesh.bond

[redis]
redis-dev.rakesh.bond

[user]
user-dev.rakesh.bond

[cart]
cart-dev.rakesh.bond

[mysql]
mysql-dev.rakesh.bond

[shipping]
shipping-dev.rakesh.bond

[rabbitmq]
rabbitmq-dev.rakesh.bond

[payment]
payment-dev.rakesh.bond

[frontend]
frontend-dev.rakesh.bond

[all:vars]
ansible_name=ec2_user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.rakesh.bond
REDIS_HOST=redis-dev.rakesh.bond
CATALOGUE_HOST=catalogue-dev.rakesh.bond
CART_HOST=cart-dev.rakesh.bond
PAYMENT_HOST=payment-dev.rakesh.bond
MYSQL_HOST=mysql-dev.rakesh.bond
USER_HOST=user-dev.rakesh.bond
RABBITMQ_HOST=rabbitmq-dev.rakesh.bond

