- name: Creating EC2 Instances and R53 records
  hosts: all
  connection: local
  vars:
   sg_id: sg-0978bd3e9e6d67ee8
   ami_id: ami-0220d79f3f480ecf5
   domain_name: rakesh.bond
   env: dev
   instances:
    - mongodb
    - catalogue
  tasks:
  - name: Create ec2 instance
    amazon.aws.ec2_instance:
     name: "{{ item }}-{{ env }}"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
     instance_type: t3.micro
     tags:
      Project: roboshop 
      Component: "{{ item }}"
      Environment: "{{ env }}"
      Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print output
    ansible.builtin.debug:
     msg: "{{ ec2_output }}"

  - name: create route 53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" #mogodb-dev.rakesh.bondS
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: false
    loop: "{{ec2_output.results}}"

  - name: create route 53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshp-{{ env }}.{{ domain_name }}" #roboshop-dev.rakesh.bond
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: false
    loop: "{{ec2_output.results}}"
    when: item.item == "frontend"
    

    